# Generated by Django 5.1 on 2024-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_customer_email_remove_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image",
            field=models.ImageField(default=1, upload_to="api/images"),
            preserve_default=False,
        ),
    ]
