# Generated by Django 5.1 on 2024-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_meal_calories"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="meal",
            name="image",
            field=models.ImageField(unique=True, upload_to="api/images"),
        ),
    ]
