# Generated by Django 5.1 on 2024-09-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_customer_email_alter_meal_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
            preserve_default=False,
        ),
    ]
