# Generated by Django 5.1 on 2024-09-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_customer_email_mealplan_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.customer",
            ),
        ),
    ]
