# Generated by Django 5.1 on 2024-09-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_customer_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="meal_plan",
        ),
    ]
