# Generated by Django 5.1 on 2024-09-13 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="api.customer",
            ),
        ),
    ]
