# Generated by Django 5.1 on 2024-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_customeraddress_delete_mealplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="postcode",
        ),
    ]
