# Generated by Django 5.1 on 2024-09-17 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_customer_address_remove_customer_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_detail",
                to="api.customer",
            ),
        ),
    ]
