# Generated by Django 5.1 on 2024-09-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_customeraddress_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_details",
                to="api.customer",
            ),
        ),
    ]
