# Generated by Django 5.1 on 2024-09-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_customeraddress_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_address",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.customeraddress",
            ),
            preserve_default=False,
        ),
    ]
