# Generated by Django 5.1 on 2024-09-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_order_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protein_preference",
                    models.CharField(
                        choices=[
                            ("MO", "Meat Only"),
                            ("MV", "Meat and Vegan"),
                            ("VO", "Vegan Only"),
                        ],
                        default="MO",
                        max_length=2,
                    ),
                ),
                (
                    "meal_size",
                    models.CharField(
                        choices=[("S", "Standard"), ("L", "Large")],
                        default="S",
                        max_length=1,
                    ),
                ),
                ("number_of_meals", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
