# Generated by Django 5.1 on 2024-09-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_mealplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_price", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
