# Generated by Django 5.1 on 2024-10-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_order_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
    ]
